name: Publish to PyPi

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "^3.8"
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Build package
      run: poetry build
    - name: Publish package
      run: |
        # 'export POETRY_PYPI_TOKEN_PYPI=my-token' does not seem to work and prompts for username/password
        # therefore we use the below username/password option instead
        export POETRY_HTTP_BASIC_PYPI_USERNAME=__token__
        export POETRY_HTTP_BASIC_PYPI_PASSWORD=${{ secrets.PYPI_API_TOKEN }}
        poetry publish
